version: '3.8'
services:
  mongo:
    image: mongo:latest
    container_name: ms_mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
  nginx:
    build: ./nginx
    container_name: ms_nginx
    links:
      - store
      - users
    ports:

  store:
    build: ./store
    container_name: ms_store
    depends_on:
      - "mongo"
    volumes:
      - ./store:/src/app
    working_dir: /src/app
    ports:
      - "3004:3000"
    
    command: npm run start
  users:
    build: ./users
    container_name: ms_user
    depends_on:
      - "mongo"
    volumes:
      - ./users:/src/app
    working_dir: /src/app
    ports:
      - "3006:3000"
    command: npm run start